#!/usr/bin/env bash
# Write the cluster-specific NetworkPolicy and HCC patches for
# deploy/overlays/aws-eks from values detected in Phase 0.5. Never hand-edit
# CIDRs into these files; re-run this script instead (also after every EKS
# control-plane version upgrade, which replaces the API server ENIs).
#
# Required env:
#   OVERLAY_DIR    path to deploy/overlays/aws-eks in the release checkout
#   API_IPS        space-separated IPv4: kubernetes Service ClusterIP + every endpoint
#   DNS_IP         kube-dns Service ClusterIP (IPv4)
#   STORAGE_CLASS  RWO block StorageClass for HCC workspaces (e.g. gp3)
# Optional env:
#   NODELOCAL_DNS_IP  single NodeLocal DNSCache IPv4, only if node-local-dns runs
#   INGRESS_CIDRS     space-separated IPv4 CIDRs the ALB/NLB reaches pods from
#                     (ALB IP target mode: the ALB subnets). Omit for Cloudflare Tunnel.
set -euo pipefail

: "${OVERLAY_DIR:?set OVERLAY_DIR}"
: "${API_IPS:?set API_IPS}"
: "${DNS_IP:?set DNS_IP}"
: "${STORAGE_CLASS:?set STORAGE_CLASS}"
NODELOCAL_DNS_IP="${NODELOCAL_DNS_IP:-}"
INGRESS_CIDRS="${INGRESS_CIDRS:-}"

die() { printf 'write-network-patches: STOP: %s\n' "$*" >&2; exit 1; }
is_ipv4() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; }
is_ipv4_cidr() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$ ]]; }

[ -f "$OVERLAY_DIR/kustomization.yaml" ] || die "$OVERLAY_DIR/kustomization.yaml not found"
for ip in $API_IPS; do is_ipv4 "$ip" || die "API_IPS entry '$ip' is not IPv4 (IPv6 clusters are not covered by this guide)"; done
is_ipv4 "$DNS_IP" || die "DNS_IP '$DNS_IP' is not IPv4"
[ -z "$NODELOCAL_DNS_IP" ] || is_ipv4 "$NODELOCAL_DNS_IP" || die "NODELOCAL_DNS_IP is not a single IPv4"
for c in $INGRESS_CIDRS; do is_ipv4_cidr "$c" || die "INGRESS_CIDRS entry '$c' is not an IPv4 CIDR"; done
[ -n "$(printf '%s' "$API_IPS" | tr -d ' ')" ] || die "API_IPS is empty"

mkdir -p "$OVERLAY_DIR/patches"
api_ip_list="$(printf '%s\n' $API_IPS | awk 'NF' | sort -u)"
api_cidr_csv="$(printf '%s\n' "$api_ip_list" | sed 's#$#/32#' | paste -sd, -)"

ipblocks() {
  local indent="$1"; shift
  local x
  for x in "$@"; do
    printf '%s- ipBlock:\n%s    cidr: %s\n' "$indent" "$indent" "$x"
  done
}

{
  printf '# Generated by write-network-patches.sh. Re-run; do not hand-edit.\n'
  for ns in control-plane channels mcp-host; do
    printf -- '---\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: allow-k8s-api-egress-%s\n  namespace: %s\nspec:\n  egress:\n    - to:\n' "$ns" "$ns"
    # shellcheck disable=SC2046
    ipblocks '        ' $(printf '%s\n' "$api_ip_list" | sed 's#$#/32#')
    printf '      ports:\n        - port: 443\n          protocol: TCP\n'
    if [ "$ns" = mcp-host ]; then
      printf '        - port: 8443\n          protocol: TCP\n'
    fi
  done
} >"$OVERLAY_DIR/patches/k8s-api-ip.yaml"

cat >"$OVERLAY_DIR/patches/hcc-cluster.yaml" <<EOF
# Generated by write-network-patches.sh. Re-run; do not hand-edit.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-context-controller
  namespace: control-plane
spec:
  template:
    spec:
      containers:
        - name: host-context-controller
          env:
            - name: CONTEXT_MAPPER_K8S_API_CIDRS
              value: "${api_cidr_csv}"
            - name: CONTEXT_MAPPER_NODELOCAL_DNS_CIDR
              value: "${NODELOCAL_DNS_IP:+${NODELOCAL_DNS_IP}/32}"
            - name: CONTEXT_MAPPER_HOST_WORKSPACE_STORAGE_CLASS
              value: "${STORAGE_CLASS}"
EOF

dns_cidrs=("${DNS_IP}/32")
[ -z "$NODELOCAL_DNS_IP" ] || dns_cidrs+=("${NODELOCAL_DNS_IP}/32")
{
  printf '# Generated by write-network-patches.sh. Re-run; do not hand-edit.\n'
  printf -- '- op: add\n  path: /spec/egress/-\n  value:\n    to:\n'
  ipblocks '      ' "${dns_cidrs[@]}"
  printf '    ports:\n      - port: 53\n        protocol: UDP\n      - port: 53\n        protocol: TCP\n'
} >"$OVERLAY_DIR/patches/kube-dns-egress-rule.yaml"

write_ingress_patch() {
  local file="$1"; shift
  local port
  {
    printf '# Generated by write-network-patches.sh. Re-run; do not hand-edit.\n'
    printf -- '- op: add\n  path: /spec/ingress/-\n  value:\n    from:\n'
    # shellcheck disable=SC2086
    ipblocks '      ' $INGRESS_CIDRS
    printf '    ports:\n'
    for port in "$@"; do
      printf '      - port: %s\n        protocol: TCP\n' "$port"
    done
  } >"$OVERLAY_DIR/patches/$file"
}

if [ -n "$INGRESS_CIDRS" ]; then
  write_ingress_patch alb-ingress-control-ui.yaml 3000
  write_ingress_patch alb-ingress-profiles.yaml 3001 8091
  write_ingress_patch alb-ingress-rpc-proxy.yaml 8094
  write_ingress_patch alb-ingress-webhook-proxy.yaml 8095
else
  rm -f "$OVERLAY_DIR"/patches/alb-ingress-*.yaml
fi

printf 'write-network-patches: wrote patches for API [%s], DNS [%s], ingress [%s]\n' \
  "$api_cidr_csv" "${dns_cidrs[*]}" "${INGRESS_CIDRS:-none}"
