#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
# E2E Runner — example-dev (GKE) Airtable registry + XLSX report suite
# ═══════════════════════════════════════════════════════════════════════
#
# Boots port-forwards against the example-dev GKE cluster, runs the
# Airtable registry E2E spec
# (control-ui/e2e/registry-airtable-e2e.spec.ts), then tears the
# port-forwards down — regardless of success or failure.
#
# The spec installs the Airtable MCP server from the registry with real
# credentials, exercises the chatllm agent end-to-end (list/create/query/
# delete records), and validates an XLSX artifact generated by the
# clerum__generate_xlsx internal tool.
#
# WHY A WRAPPER (AND NOT `make gcp-dev-pf-all`):
#   The Makefile target uses `wait` which blocks indefinitely. This wrapper
#   owns the PF lifecycle so we can launch them, wait for readiness, run
#   Playwright, and reap them on exit via `trap`.
#
# Prerequisites:
#   - gcloud auth + `gcloud container clusters get-credentials example-dev`
#     has already populated the GKE_DEV context in kubeconfig
#   - `npm ci` inside control-ui/ (Playwright + browsers)
#   - jq, curl on PATH
#   - AIRTABLE_API_KEY and AIRTABLE_BASE_ID exported (see spec header)
#
# Env overrides:
#   CONTEXT            — kubectl context
#                        (default: gke_${GCP_PROJECT}_us-central1-a_example-dev)
#   ADMIN_USER         — admin username (default: admin)
#   ADMIN_PASS         — admin password (default: changeme123!)
#   SPEC               — Playwright spec path
#                        (default: e2e/registry-airtable-e2e.spec.ts)
#   AIRTABLE_API_KEY   — REQUIRED Airtable personal access token
#   AIRTABLE_BASE_ID   — REQUIRED Airtable base ID (e.g. appXXXXXXXXXXXXXX)
#
# Exit code: propagates Playwright's.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# ─── Auto-load .env ───────────────────────────────────────────────────
# Same contract as scripts/e2e/run-e2e-minikube-registry.sh: the Airtable
# spec expects AIRTABLE_API_KEY and AIRTABLE_BASE_ID in the process env,
# and the project convention (see registry-airtable-e2e.spec.ts header
# line 17) is that those creds live in `.env`. Source it so the `:?`
# check below finds the value without requiring the user to remember
# `export $(grep -v ^# .env | xargs)` every time.
#
# Caller-provided env vars still win: `set -a` re-exports everything,
# but the shell won't overwrite a var that's already set unless the .env
# line explicitly reassigns it.
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091  # .env path is known at runtime
  . "$REPO_ROOT/.env"
  set +a
fi

CONTEXT="${CONTEXT:-gke_${GCP_PROJECT}_us-central1-a_example-dev}"
ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASS="${ADMIN_PASS:-changeme123!}"
SPEC="${SPEC:-e2e/registry-airtable-e2e.spec.ts}"

UI_PORT=3000
API_PORT=8090
UI_NS=control-plane
API_NS=control-plane
UI_SVC=control-ui
API_SVC=control-api

log()  { printf '[e2e-example-dev-airtable] %s\n' "$*" >&2; }
die()  { printf '[e2e-example-dev-airtable] ERROR: %s\n' "$*" >&2; exit 1; }

# ─── Prerequisite checks ──────────────────────────────────────────────
command -v kubectl >/dev/null 2>&1 || die "kubectl not on PATH"
command -v jq      >/dev/null 2>&1 || die "jq not on PATH"
command -v curl    >/dev/null 2>&1 || die "curl not on PATH"
command -v npx     >/dev/null 2>&1 || die "npx not on PATH"

# Airtable credentials are mandatory — the spec uses test.skip() when they
# are missing, which would silently pass zero tests. Fail loud instead so
# CI / humans know the run was a no-op.
: "${AIRTABLE_API_KEY:?AIRTABLE_API_KEY is required (export your Airtable personal access token)}"
: "${AIRTABLE_BASE_ID:?AIRTABLE_BASE_ID is required (export your Airtable base ID, e.g. appXXXXXXXXXXXXXX)}"

# Context must exist; fail fast with a readable error rather than a
# cryptic kubectl "context not found" later inside the PF loop.
if ! kubectl config get-contexts -o name | grep -Fxq "$CONTEXT"; then
  die "kubectl context '$CONTEXT' not found. Run 'gcloud container clusters get-credentials example-dev --zone us-central1-a --project ${GCP_PROJECT}' first."
fi

# Reject if the literal dev services aren't reachable — typical on a
# freshly-torn-down cluster. Cheaper to fail here than during port-forward.
kubectl --context "$CONTEXT" get svc "$UI_SVC"  -n "$UI_NS"  >/dev/null 2>&1 || die "svc/$UI_SVC not found in $UI_NS on $CONTEXT"
kubectl --context "$CONTEXT" get svc "$API_SVC" -n "$API_NS" >/dev/null 2>&1 || die "svc/$API_SVC not found in $API_NS on $CONTEXT"

# ─── Port-forward lifecycle ───────────────────────────────────────────
PF_PIDS=()
cleanup() {
  local ec=$?
  if [ ${#PF_PIDS[@]} -gt 0 ]; then
    log "Tearing down ${#PF_PIDS[@]} port-forward(s)"
    for pid in "${PF_PIDS[@]}"; do
      kill "$pid" 2>/dev/null || true
    done
    # Give kubectl a moment to close sockets before the script exits;
    # avoids "address already in use" on rapid re-runs.
    wait 2>/dev/null || true
  fi
  exit "$ec"
}
trap cleanup EXIT INT TERM

log "Starting port-forwards against $CONTEXT"
kubectl --context "$CONTEXT" port-forward "svc/$UI_SVC"  -n "$UI_NS"  "${UI_PORT}:${UI_PORT}"   >/tmp/pf-control-ui.log  2>&1 &
PF_PIDS+=($!)
kubectl --context "$CONTEXT" port-forward "svc/$API_SVC" -n "$API_NS" "${API_PORT}:${API_PORT}" >/tmp/pf-control-api.log 2>&1 &
PF_PIDS+=($!)

# Wait for PFs to bind. We poll both endpoints because kubectl's PID
# appears immediately but the TCP bind happens a few ms later, and the
# first Playwright request would race and get ECONNREFUSED.
log "Waiting for port-forwards to become ready..."
for i in $(seq 1 40); do
  ui_ok=0 api_ok=0
  curl -fsS -o /dev/null --max-time 2 "http://localhost:${UI_PORT}"           && ui_ok=1 || true
  # /health is public; prefer it over /api/* which requires auth
  curl -fsS -o /dev/null --max-time 2 "http://localhost:${API_PORT}/health"   && api_ok=1 || true
  if [ "$ui_ok" = 1 ] && [ "$api_ok" = 1 ]; then
    log "  ✓ UI=:${UI_PORT} API=:${API_PORT} are reachable"
    break
  fi
  if [ "$i" = 40 ]; then
    log "Port-forwards did not become ready in 20s. Logs:"
    log "--- /tmp/pf-control-ui.log ---"
    tail -n 20 /tmp/pf-control-ui.log >&2 || true
    log "--- /tmp/pf-control-api.log ---"
    tail -n 20 /tmp/pf-control-api.log >&2 || true
    die "Port-forward readiness timeout"
  fi
  sleep 0.5
done

# ─── Run Playwright ───────────────────────────────────────────────────
cd "$REPO_ROOT/control-ui"

# The Airtable spec runs 8-min per workflow × multiple workflows; a 15-min
# Playwright-level timeout keeps the whole suite from being cut short.
log "Running Playwright Airtable spec: $SPEC"
CONTROL_API_URL="http://localhost:${API_PORT}" \
CONTROL_UI_URL="http://localhost:${UI_PORT}" \
ADMIN_USER="$ADMIN_USER" \
ADMIN_PASS="$ADMIN_PASS" \
AIRTABLE_API_KEY="$AIRTABLE_API_KEY" \
AIRTABLE_BASE_ID="$AIRTABLE_BASE_ID" \
npx playwright test "$SPEC" --reporter=list --timeout=900000
