module.exports = {
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  printWidth: 100,
  bracketSpacing: true,
  arrowParens: 'avoid',
  importOrder: [
    '^react$',
    '^react-dom$',
    '^next(/.*)?$',
    '^vitest(?:/.*)?$',
    '^express$',
    '^@modelcontextprotocol/sdk$',
    '^@kubernetes/client-node$',
    '<THIRD_PARTY_MODULES>',
    '^@clerum/(.*)$',
    '^@components/(.*)$',
    '^@constants/(.*)$',
    '^@hooks/(.*)$',
    '^@lib/(.*)$',
    '^@pages/(.*)$',
    '^@styles/(.*)$',
    '^@types/(.*)$',
    '^@utils/(.*)$',
    '^@/(.*)$',
    '^[./]',
  ],
  importOrderSortSpecifiers: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
}
