#!/usr/bin/env bash
# Adapted from .agents/skills/evenfire-aws-eks/scripts/write-network-patches.sh (PR #626 @ b21b5a982).
#
# Write the cluster-specific network files for deploy/overlays/digitalocean-doks
# from values detected by doks-discover.sh. Never hand-edit these files; re-run
# this script instead (also after every DOKS upgrade or node replacement).
#
# On DOKS the Kubernetes API server is reached through CiliumNetworkPolicy
# `toEntities: kube-apiserver` (DigitalOcean documents that a NetworkPolicy
# cannot selectively allow API-server access), so this script writes:
#   patches/k8s-api-ip.yaml           ipBlock API egress (kept for np-enforce-preflight check 2)
#   patches/hcc-cluster.yaml          HCC API CIDRs, NodeLocal DNS CIDR, workspace StorageClass
#   patches/kube-dns-egress-rule.yaml DNS egress rule for every allow-dns-egress-* policy
#   patches/cilium-api-egress.yaml    the load-bearing API egress grants (a resource, not a patch)
#   patches/ingress-controller-*.yaml INGRESS_MODE=controller only: admit the in-cluster
#                                     ingress controller pods by selector
#
# Required env:
#   OVERLAY_DIR        path to deploy/overlays/digitalocean-doks in the release checkout
#   API_IPS            space-separated IPv4: kubernetes Service ClusterIP + every endpoint
#   API_ENDPOINT_PORT  port of the kubernetes EndpointSlice (Cilium may evaluate
#                      policy after translating ClusterIP:443 to endpoint:port)
#   DNS_IP             kube-dns Service ClusterIP (IPv4)
#   STORAGE_CLASS      RWO block StorageClass for HCC Host workspaces
#   INGRESS_MODE       controller | tunnel
# Required when INGRESS_MODE=controller (read both from the live controller pods):
#   INGRESS_NAMESPACE  namespace of the ingress controller (e.g. Traefik)
#   INGRESS_POD_LABELS comma-separated key=value labels of the controller pods
# Optional env:
#   NODELOCAL_DNS_IP   single NodeLocal DNSCache IPv4, only if node-local-dns runs
set -euo pipefail

: "${OVERLAY_DIR:?set OVERLAY_DIR}"
: "${API_IPS:?set API_IPS}"
: "${API_ENDPOINT_PORT:?set API_ENDPOINT_PORT}"
: "${DNS_IP:?set DNS_IP}"
: "${STORAGE_CLASS:?set STORAGE_CLASS}"
: "${INGRESS_MODE:?set INGRESS_MODE to controller or tunnel}"
NODELOCAL_DNS_IP="${NODELOCAL_DNS_IP:-}"
INGRESS_NAMESPACE="${INGRESS_NAMESPACE:-}"
INGRESS_POD_LABELS="${INGRESS_POD_LABELS:-}"

die() { printf 'write-network-patches: STOP: %s\n' "$*" >&2; exit 1; }
is_ipv4() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; }
is_name() { [[ "$1" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]]; }

[ -f "$OVERLAY_DIR/kustomization.yaml" ] || die "$OVERLAY_DIR/kustomization.yaml not found"
for ip in $API_IPS; do is_ipv4 "$ip" || die "API_IPS entry '$ip' is not IPv4 (DOKS does not support IPv6 clusters)"; done
[ -n "$(printf '%s' "$API_IPS" | tr -d ' ')" ] || die "API_IPS is empty"
[[ "$API_ENDPOINT_PORT" =~ ^[0-9]{1,5}$ ]] && [ "$API_ENDPOINT_PORT" -ge 1 ] && [ "$API_ENDPOINT_PORT" -le 65535 ] \
  || die "API_ENDPOINT_PORT '$API_ENDPOINT_PORT' is not a TCP port"
is_ipv4 "$DNS_IP" || die "DNS_IP '$DNS_IP' is not IPv4"
[ -z "$NODELOCAL_DNS_IP" ] || is_ipv4 "$NODELOCAL_DNS_IP" || die "NODELOCAL_DNS_IP is not a single IPv4"
case "$INGRESS_MODE" in
  controller)
    is_name "$INGRESS_NAMESPACE" || die "INGRESS_MODE=controller needs INGRESS_NAMESPACE"
    [ -n "$INGRESS_POD_LABELS" ] || die "INGRESS_MODE=controller needs INGRESS_POD_LABELS (read them from the controller pods)"
    IFS=',' read -r -a ingress_labels <<<"$INGRESS_POD_LABELS"
    for l in "${ingress_labels[@]}"; do
      [[ "$l" =~ ^[A-Za-z0-9./_-]+=[A-Za-z0-9._-]+$ ]] || die "INGRESS_POD_LABELS entry '$l' is not key=value"
    done ;;
  tunnel) ;;
  *) die "INGRESS_MODE must be controller or tunnel (Gateway API traffic carries Cilium's ingress identity, which a NetworkPolicy cannot select)" ;;
esac

mkdir -p "$OVERLAY_DIR/patches"
api_ip_list="$(printf '%s\n' $API_IPS | awk 'NF' | sort -u)"
api_cidr_csv="$(printf '%s\n' "$api_ip_list" | sed 's#$#/32#' | paste -sd, -)"
header='# Generated by write-network-patches.sh. Re-run; do not hand-edit.'

ipblocks() {
  local indent="$1"; shift
  local x
  for x in "$@"; do
    printf '%s- ipBlock:\n%s    cidr: %s\n' "$indent" "$indent" "$x"
  done
}

{
  printf '%s\n' "$header"
  printf '# On DOKS these ipBlocks are not what grants API access (see cilium-api-egress.yaml);\n'
  printf '# they keep np-enforce-preflight.sh check 2 and verify-networkpolicies.sh consistent.\n'
  for ns in control-plane channels mcp-host; do
    printf -- '---\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: allow-k8s-api-egress-%s\n  namespace: %s\nspec:\n  egress:\n    - to:\n' "$ns" "$ns"
    # shellcheck disable=SC2046
    ipblocks '        ' $(printf '%s\n' "$api_ip_list" | sed 's#$#/32#')
    printf '      ports:\n        - port: 443\n          protocol: TCP\n'
    if [ "$ns" = mcp-host ]; then
      printf '        - port: 8443\n          protocol: TCP\n'
    fi
  done
} >"$OVERLAY_DIR/patches/k8s-api-ip.yaml"

cat >"$OVERLAY_DIR/patches/hcc-cluster.yaml" <<EOF
${header}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-context-controller
  namespace: control-plane
spec:
  template:
    spec:
      containers:
        - name: host-context-controller
          env:
            - name: CONTEXT_MAPPER_K8S_API_CIDRS
              value: "${api_cidr_csv}"
            - name: CONTEXT_MAPPER_NODELOCAL_DNS_CIDR
              value: "${NODELOCAL_DNS_IP:+${NODELOCAL_DNS_IP}/32}"
            - name: CONTEXT_MAPPER_HOST_WORKSPACE_STORAGE_CLASS
              value: "${STORAGE_CLASS}"
EOF

dns_cidrs=("${DNS_IP}/32")
[ -z "$NODELOCAL_DNS_IP" ] || dns_cidrs+=("${NODELOCAL_DNS_IP}/32")
{
  printf '%s\n' "$header"
  printf -- '- op: add\n  path: /spec/egress/-\n  value:\n    to:\n'
  ipblocks '      ' "${dns_cidrs[@]}"
  printf '    ports:\n      - port: 53\n        protocol: UDP\n      - port: 53\n        protocol: TCP\n'
} >"$OVERLAY_DIR/patches/kube-dns-egress-rule.yaml"

# CiliumNetworkPolicies mirror the API-egress NetworkPolicy selectors at v0.10.0:
#   control-plane  deploy/base/control-plane/networkpolicies.yaml (allow-k8s-api-egress-control-plane)
#   channels       deploy/base/channels/networkpolicies/k8s-api-egress.yaml
#   mcp-host       deploy/base/mcp-host/networkpolicies.yaml (443 and 8443)
#   mcp-server, sandbox-recipes, rpc-proxy: HCC networkPolicyReconciler.ts
#     k8sApiEgressPodSelector opt-in label. No pod sets that label at v0.10.0,
#     so these three grant nothing today; they keep the opt-in working on DOKS.
cnp_ports() {
  local p
  for p in "$@"; do
    printf '            - port: "%s"\n              protocol: TCP\n' "$p"
  done
}
cnp() { # namespace selector-yaml extra-port...
  local ns="$1" selector="$2"; shift 2
  local ports
  ports="$(printf '%s\n' 443 "$API_ENDPOINT_PORT" "$@" | sort -un)"
  # shellcheck disable=SC2086
  printf -- '---\napiVersion: cilium.io/v2\nkind: CiliumNetworkPolicy\nmetadata:\n  name: allow-k8s-api-egress-cilium-%s\n  namespace: %s\nspec:\n  endpointSelector:\n%s\n  egress:\n    - toEntities: [kube-apiserver]\n      toPorts:\n        - ports:\n%s\n' \
    "$ns" "$ns" "$selector" "$(cnp_ports $ports)"
}
optin='    matchLabels:
      clerum.io/k8s-api-egress: "true"'
{
  printf '%s\n' "$header"
  printf '# DOKS: NetworkPolicy ipBlocks cannot select the API server (DigitalOcean known\n'
  printf '# issue); these CiliumNetworkPolicies are the load-bearing API egress grants.\n'
  cnp control-plane '    matchExpressions:
      - key: app
        operator: In
        values: [host-context-controller, workflow-recipes, control-api, trace-maintenance-worker]'
  cnp channels '    matchLabels:
      app: channel-reader'
  cnp mcp-host '    matchLabels:
      clerum.io/managed-by: host-context-controller' 8443
  cnp mcp-server "$optin"
  cnp sandbox-recipes "$optin"
  cnp rpc-proxy "$optin"
} >"$OVERLAY_DIR/patches/cilium-api-egress.yaml"

write_ingress_patch() {
  local file="$1"; shift
  local port l
  {
    printf '%s\n' "$header"
    printf -- '- op: add\n  path: /spec/ingress/-\n  value:\n    from:\n'
    printf '      - namespaceSelector:\n          matchLabels:\n            kubernetes.io/metadata.name: %s\n' "$INGRESS_NAMESPACE"
    printf '        podSelector:\n          matchLabels:\n'
    for l in "${ingress_labels[@]}"; do
      printf '            %s: %s\n' "${l%%=*}" "${l#*=}"
    done
    printf '    ports:\n'
    for port in "$@"; do
      printf '      - port: %s\n        protocol: TCP\n' "$port"
    done
  } >"$OVERLAY_DIR/patches/$file"
}

rm -f "$OVERLAY_DIR"/patches/ingress-controller-*.yaml
if [ "$INGRESS_MODE" = controller ]; then
  write_ingress_patch ingress-controller-control-ui.yaml 3000
  write_ingress_patch ingress-controller-profiles.yaml 3001 8091
  write_ingress_patch ingress-controller-rpc-proxy.yaml 8094
  write_ingress_patch ingress-controller-webhook-proxy.yaml 8095
fi

printf 'write-network-patches: wrote patches for API [%s] endpoint port %s, DNS [%s], ingress %s\n' \
  "$api_cidr_csv" "$API_ENDPOINT_PORT" "${dns_cidrs[*]}" "$INGRESS_MODE"
