// Generated from scripts/conversation-store/verify-inline.mjs; contract tests verify exact bytes.
// HCC executes this source through authenticated Exec, never a tenant-writable file.
export const CONVERSATION_STORE_BOOTSTRAP_VERIFY_PROGRAM = [
  'import * as fs from "node:fs";\n',
  'import * as path from "node:path";\n',
  'import * as https from "node:https";\n',
  'import { createHash } from "node:crypto";\n',
  'import { parseArgs } from "node:util";\n',
  'import { fileURLToPath } from "node:url";\n',
  'import { createRequire } from "node:module";\n',
  '\n',
  'export const SQLITE_NAMES = [\n',
  '  "state.db",\n',
  '  "state.db-wal",\n',
  '  "state.db-shm",\n',
  '  "state.db-journal",\n',
  '];\n',
  'export function blocked(reason) {\n',
  '  const error = new Error(reason);\n',
  '  error.reason = reason;\n',
  '  throw error;\n',
  '}\n',
  'export function stableJson(value) {\n',
  '  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;\n',
  '  if (value && typeof value === "object")\n',
  '    return `{${Object.keys(value)\n',
  '      .sort()\n',
  '      .filter((key) => value[key] !== undefined)\n',
  '      .map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`)\n',
  '      .join(",")}}`;\n',
  '  return JSON.stringify(value);\n',
  '}\n',
  '// Deliberately identical to canonicalStore/paths.objectHash; parity is tested.\n',
  'export const objectHash = (value) =>\n',
  '  createHash("sha256").update(stableJson(value)).digest("hex");\n',
  'export function regular(\n',
  '  file,\n',
  '  { owner, readonly = false, maximum = 8 * 1024 * 1024 } = {},\n',
  ') {\n',
  '  const stat = fs.lstatSync(file);\n',
  '  if (\n',
  '    !stat.isFile() ||\n',
  '    stat.isSymbolicLink() ||\n',
  '    stat.nlink !== 1 ||\n',
  '    stat.size > maximum ||\n',
  '    (owner !== undefined && stat.uid !== owner) ||\n',
  '    (readonly && stat.mode & 0o022)\n',
  '  )\n',
  '    blocked("LayoutUnsafe");\n',
  '  return stat;\n',
  '}\n',
  'export function confined(root, file) {\n',
  '  const base = fs.realpathSync(root);\n',
  '  const relative = path.relative(base, path.resolve(file));\n',
  '  if (\n',
  '    relative === ".." ||\n',
  '    relative.startsWith("../") ||\n',
  '    path.isAbsolute(relative)\n',
  '  )\n',
  '    blocked("LayoutUnsafe");\n',
  '  let current = base;\n',
  '  for (const part of relative.split(path.sep).filter(Boolean)) {\n',
  '    current = path.join(current, part);\n',
  '    if (fs.lstatSync(current).isSymbolicLink()) blocked("LayoutUnsafe");\n',
  '  }\n',
  '  return current;\n',
  '}\n',
  'export function readJson(file, options = {}) {\n',
  '  regular(file, options);\n',
  '  const value = JSON.parse(fs.readFileSync(file, "utf8"));\n',
  '  if (!value || typeof value !== "object" || Array.isArray(value))\n',
  '    blocked("JournalInvalid");\n',
  '  return value;\n',
  '}\n',
  'export function fileHash(file) {\n',
  '  regular(file, { maximum: 64 * 1024 ** 3 });\n',
  '  const descriptor = fs.openSync(\n',
  '    file,\n',
  '    fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW,\n',
  '  );\n',
  '  const buffer = Buffer.alloc(1024 * 1024);\n',
  '  const digest = createHash("sha256");\n',
  '  try {\n',
  '    let count;\n',
  '    while ((count = fs.readSync(descriptor, buffer, 0, buffer.length, null)))\n',
  '      digest.update(buffer.subarray(0, count));\n',
  '  } finally {\n',
  '    fs.closeSync(descriptor);\n',
  '  }\n',
  '  return digest.digest("hex");\n',
  '}\n',
  'export function processIdentity(pid, procRoot = "/proc") {\n',
  '  if (!Number.isSafeInteger(pid) || pid < 1) blocked("WriterIdentityUnknown");\n',
  '  const directory = path.join(procRoot, String(pid));\n',
  '  try {\n',
  '    const statText = fs.readFileSync(path.join(directory, "stat"), "utf8");\n',
  '    const suffix = statText\n',
  '      .slice(statText.lastIndexOf(")") + 2)\n',
  '      .trim()\n',
  '      .split(/\\s+/);\n',
  '    const status = fs.readFileSync(path.join(directory, "status"), "utf8");\n',
  '    const identities = status.match(/^Uid:\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)/m);\n',
  '    const uid = Number(identities?.[1]);\n',
  '    if (\n',
  '      !identities ||\n',
  '      identities.slice(1).some((value) => Number(value) !== uid)\n',
  '    )\n',
  '      blocked("WriterIdentityUnknown");\n',
  '    const argv = fs\n',
  '      .readFileSync(path.join(directory, "cmdline"))\n',
  '      .toString("utf8")\n',
  '      .split("\\0")\n',
  '      .filter(Boolean);\n',
  '    if (\n',
  '      !Number.isSafeInteger(uid) ||\n',
  '      !/^\\d+$/.test(suffix[19]) ||\n',
  '      argv.length === 0\n',
  '    )\n',
  '      blocked("WriterIdentityUnknown");\n',
  '    return {\n',
  '      pid,\n',
  '      uid,\n',
  '      startTimeTicks: suffix[19],\n',
  '      executable: fs.realpathSync(path.join(directory, "exe")),\n',
  '      argv,\n',
  '      argvHash: objectHash(argv),\n',
  '    };\n',
  '  } catch (error) {\n',
  '    if (error.code === "ENOENT" && !fs.existsSync(directory)) return undefined;\n',
  '    throw error;\n',
  '  }\n',
  '}\n',
  'export function noSqliteHandles(sourcePaths, procRoot = "/proc") {\n',
  '  const names = new Set(\n',
  '    sourcePaths.flatMap((file) => [\n',
  '      file,\n',
  '      `${file}-wal`,\n',
  '      `${file}-shm`,\n',
  '      `${file}-journal`,\n',
  '    ]),\n',
  '  );\n',
  '  for (const name of fs\n',
  '    .readdirSync(procRoot)\n',
  '    .filter((name) => /^\\d+$/.test(name))) {\n',
  '    const directory = path.join(procRoot, name, "fd");\n',
  '    let descriptors;\n',
  '    try {\n',
  '      descriptors = fs.readdirSync(directory);\n',
  '    } catch (error) {\n',
  '      if (error.code === "ENOENT" && !fs.existsSync(path.join(procRoot, name)))\n',
  '        continue;\n',
  '      blocked("WriterIdentityUnknown");\n',
  '    }\n',
  '    for (const descriptor of descriptors) {\n',
  '      let target;\n',
  '      try {\n',
  '        target = fs\n',
  '          .readlinkSync(path.join(directory, descriptor))\n',
  '          .replace(/ \\(deleted\\)$/, "");\n',
  '      } catch (error) {\n',
  '        if (error.code === "ENOENT") continue;\n',
  '        blocked("WriterIdentityUnknown");\n',
  '      }\n',
  '      if (names.has(target)) blocked("WriterFenceBusy");\n',
  '    }\n',
  '  }\n',
  '}\n',
  'export function validateChallenge(host, subject, pins, operation) {\n',
  '  const store = host?.status?.conversationStore;\n',
  '  const request = store?.request;\n',
  '  const result = store?.requestResult;\n',
  '  const maintenance = store?.maintenance;\n',
  '  const ownPod =\n',
  '    subject?.status?.userInfo?.extra?.["authentication.kubernetes.io/pod-uid"];\n',
  '  if (\n',
  '    !Array.isArray(ownPod) ||\n',
  '    ownPod.length !== 1 ||\n',
  '    ownPod[0] !== pins.podUid\n',
  '  )\n',
  '    blocked("PodIdentityUnknown");\n',
  '  if (\n',
  '    host.metadata?.uid !== pins.hostUid ||\n',
  '    host.metadata?.name !== pins.hostName ||\n',
  '    host.metadata?.namespace !== pins.namespace ||\n',
  '    !request ||\n',
  '    request.schemaVersion !== 1 ||\n',
  '    request.operation !== operation ||\n',
  '    request.requestId !== pins.requestId ||\n',
  '    request.hostUid !== pins.hostUid ||\n',
  '    request.pvcUid !== pins.pvcUid ||\n',
  '    request.maintenanceId !== pins.maintenanceId ||\n',
  '    request.principal?.kind !== "control-admin" ||\n',
  '    typeof request.principal.subject !== "string" ||\n',
  '    !request.principal.subject ||\n',
  '    !result ||\n',
  '    result.requestId !== pins.requestId ||\n',
  '    result.hostUid !== pins.hostUid ||\n',
  '    result.pvcUid !== pins.pvcUid ||\n',
  '    !["accepted", "completed"].includes(result.state) ||\n',
  '    !maintenance ||\n',
  '    maintenance.hostUid !== pins.hostUid ||\n',
  '    maintenance.pvcUid !== pins.pvcUid ||\n',
  '    maintenance.maintenanceId !== pins.maintenanceId ||\n',
  '    !["quiescing", "fenced", "migrating", "completing", "completed"].includes(\n',
  '      maintenance.phase,\n',
  '    )\n',
  '  )\n',
  '    blocked("MigrationMaintenanceRequired");\n',
  '  if (\n',
  '    operation === "prepare" &&\n',
  '    (request.sourceClass !== pins.sourceClass ||\n',
  '      request.exportId !== pins.exportId ||\n',
  '      request.manifestHash !== pins.manifestHash)\n',
  '  )\n',
  '    blocked("AdoptBindingMismatch");\n',
  '  return objectHash(request);\n',
  '}\n',
  'export async function freshChallenge(pins, operation) {\n',
  '  const address = process.env.KUBERNETES_SERVICE_HOST;\n',
  '  const port = Number(\n',
  '    process.env.KUBERNETES_SERVICE_PORT_HTTPS ??\n',
  '      process.env.KUBERNETES_SERVICE_PORT,\n',
  '  );\n',
  '  if (!address || !Number.isSafeInteger(port) || port < 1 || port > 65535)\n',
  '    blocked("HostAuthorityUnavailable");\n',
  '  const serviceDirectory = "/var/run/secrets/kubernetes.io/serviceaccount";\n',
  '  const ca = fs.readFileSync(path.join(serviceDirectory, "ca.crt"));\n',
  '  const authBytes = fs\n',
  '    .readFileSync(path.join(serviceDirectory, "token"), "utf8")\n',
  '    .trim();\n',
  '  if (!authBytes) blocked("HostAuthorityUnavailable");\n',
  '  async function requestJson(route, body) {\n',
  '    return new Promise((resolve, reject) => {\n',
  '      const payload = body ? JSON.stringify(body) : undefined;\n',
  '      const request = https.request(\n',
  '        {\n',
  '          hostname: address,\n',
  '          port,\n',
  '          path: route,\n',
  '          method: body ? "POST" : "GET",\n',
  '          ca,\n',
  '          rejectUnauthorized: true,\n',
  '          signal: AbortSignal.timeout(10000),\n',
  '          headers: {\n',
  '            Authorization: `Bearer ${authBytes}`,\n',
  '            ...(body\n',
  '              ? {\n',
  '                  "Content-Type": "application/json",\n',
  '                  "Content-Length": Buffer.byteLength(payload),\n',
  '                }\n',
  '              : {}),\n',
  '          },\n',
  '        },\n',
  '        (response) => {\n',
  '          const chunks = [];\n',
  '          let size = 0;\n',
  '          response.on("data", (chunk) => {\n',
  '            size += chunk.length;\n',
  '            if (size > 1024 * 1024)\n',
  '              request.destroy(new Error("HostAuthorityUnavailable"));\n',
  '            else chunks.push(chunk);\n',
  '          });\n',
  '          response.on("end", () => {\n',
  '            try {\n',
  '              if (response.statusCode !== 200 && response.statusCode !== 201)\n',
  '                blocked("HostAuthorityUnavailable");\n',
  '              resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")));\n',
  '            } catch {\n',
  '              reject(new Error("HostAuthorityUnavailable"));\n',
  '            }\n',
  '          });\n',
  '          response.on("error", () =>\n',
  '            reject(new Error("HostAuthorityUnavailable")),\n',
  '          );\n',
  '        },\n',
  '      );\n',
  '      request.setTimeout(10000, () =>\n',
  '        request.destroy(new Error("HostAuthorityUnavailable")),\n',
  '      );\n',
  '      request.on("error", () => reject(new Error("HostAuthorityUnavailable")));\n',
  '      request.end(payload);\n',
  '    });\n',
  '  }\n',
  '  const host = await requestJson(\n',
  '    `/apis/clerum.io/v1alpha1/namespaces/${encodeURIComponent(pins.namespace)}/hosts/${encodeURIComponent(pins.hostName)}`,\n',
  '  );\n',
  '  const subject = await requestJson(\n',
  '    "/apis/authentication.k8s.io/v1/selfsubjectreviews",\n',
  '    { apiVersion: "authentication.k8s.io/v1", kind: "SelfSubjectReview" },\n',
  '  );\n',
  '  return validateChallenge(host, subject, pins, operation);\n',
  '}\n',
  'export function validateRuntimeClosure(report, pins) {\n',
  '  const fields = [\n',
  '    "schemaVersion",\n',
  '    "contractVersion",\n',
  '    "hostUid",\n',
  '    "pvcUid",\n',
  '    "maintenanceId",\n',
  '    "podUid",\n',
  '    "process",\n',
  '    "source",\n',
  '    "closure",\n',
  '    "observedAt",\n',
  '  ];\n',
  '  if (\n',
  '    Object.keys(report).some((key) => !fields.includes(key)) ||\n',
  '    report.schemaVersion !== 1 ||\n',
  '    report.contractVersion !== 1 ||\n',
  '    report.closure !== "acknowledged-worker-exit" ||\n',
  '    report.hostUid !== pins.hostUid ||\n',
  '    report.pvcUid !== pins.pvcUid ||\n',
  '    report.podUid !== pins.podUid ||\n',
  '    report.maintenanceId !== pins.maintenanceId ||\n',
  '    report.source?.mode !== "sqlite" ||\n',
  '    !path.isAbsolute(report.source.dbPath ?? "") ||\n',
  '    !Number.isFinite(Date.parse(report.observedAt))\n',
  '  )\n',
  '    blocked("MigrationMaintenanceRequired");\n',
  '  if (\n',
  '    Object.keys(report.process ?? {}).some(\n',
  '      (key) =>\n',
  '        !["pid", "uid", "startTimeTicks", "executable", "script"].includes(key),\n',
  '    ) ||\n',
  '    Object.keys(report.source ?? {}).some(\n',
  '      (key) => !["mode", "dbPath"].includes(key),\n',
  '    )\n',
  '  )\n',
  '    blocked("JournalInvalid");\n',
  '  return report;\n',
  '}\n',
  'export function verifyLiveProcess(\n',
  '  report,\n',
  '  { procRoot = "/proc", expectedUid = 1001 } = {},\n',
  ') {\n',
  '  const measured = processIdentity(report.process.pid, procRoot);\n',
  '  if (\n',
  '    !measured ||\n',
  '    measured.uid !== expectedUid ||\n',
  '    report.process.uid !== expectedUid ||\n',
  '    measured.startTimeTicks !== report.process.startTimeTicks ||\n',
  '    measured.executable !== report.process.executable\n',
  '  )\n',
  '    blocked("WriterIdentityChanged");\n',
  '  const cwd = fs.realpathSync(path.join(procRoot, String(measured.pid), "cwd"));\n',
  '  const script = measured.argv[1]\n',
  '    ? fs.realpathSync(path.resolve(cwd, measured.argv[1]))\n',
  '    : "";\n',
  '  if (\n',
  '    script !== report.process.script ||\n',
  '    script !== "/app/mcp-host/dist/main.js"\n',
  '  )\n',
  '    blocked("ImageFloorMissing");\n',
  '  const allowed = [\n',
  '    "CLERUM_SESSION_STORE",\n',
  '    "CLERUM_SESSION_DB_DIR",\n',
  '    "CLERUM_SESSION_DB_PATH",\n',
  '  ];\n',
  '  const environment = Object.fromEntries(\n',
  '    fs\n',
  '      .readFileSync(path.join(procRoot, String(measured.pid), "environ"))\n',
  '      .toString("utf8")\n',
  '      .split("\\0")\n',
  '      .map((entry) => {\n',
  '        const separator = entry.indexOf("=");\n',
  '        return [entry.slice(0, separator), entry.slice(separator + 1)];\n',
  '      })\n',
  '      .filter(([name]) => allowed.includes(name)),\n',
  '  );\n',
  '  if (environment.CLERUM_SESSION_STORE !== "sqlite")\n',
  '    blocked("StoreModeUnknown");\n',
  '  const configured = environment.CLERUM_SESSION_DB_DIR\n',
  '    ? path.join(environment.CLERUM_SESSION_DB_DIR, "state.db")\n',
  '    : environment.CLERUM_SESSION_DB_PATH;\n',
  '  if (\n',
  '    !configured ||\n',
  '    !path.isAbsolute(configured) ||\n',
  '    path.resolve(configured) !== report.source.dbPath\n',
  '  )\n',
  '    blocked("SourceExportRequired");\n',
  '  return { ...measured, script, mainSha256: fileHash(script) };\n',
  '}\n',
  'export function immutableCodeTree(\n',
  '  directory,\n',
  '  { ownerUid = 0, maximum = 512 } = {},\n',
  ') {\n',
  '  let count = 0;\n',
  '  function visit(file) {\n',
  '    if (++count > maximum) blocked("ImageFloorMissing");\n',
  '    const stat = fs.lstatSync(file);\n',
  '    if (stat.isSymbolicLink() || stat.uid !== ownerUid || stat.mode & 0o022)\n',
  '      blocked("ImageFloorMissing");\n',
  '    if (stat.isDirectory())\n',
  '      for (const name of fs.readdirSync(file)) visit(path.join(file, name));\n',
  '    else\n',
  '      regular(file, {\n',
  '        owner: ownerUid,\n',
  '        readonly: true,\n',
  '        maximum: 32 * 1024 * 1024,\n',
  '      });\n',
  '  }\n',
  '  visit(directory);\n',
  '}\n',
  'export function trustedCore(appRoot = "/app/mcp-host") {\n',
  '  for (const directory of [\n',
  '    appRoot,\n',
  '    path.join(appRoot, "dist"),\n',
  '    path.join(appRoot, "node_modules"),\n',
  '  ]) {\n',
  '    const stat = fs.lstatSync(directory);\n',
  '    if (\n',
  '      !stat.isDirectory() ||\n',
  '      stat.isSymbolicLink() ||\n',
  '      stat.uid !== 0 ||\n',
  '      stat.mode & 0o022\n',
  '    )\n',
  '      blocked("ImageFloorMissing");\n',
  '  }\n',
  '  for (const directory of [\n',
  '    "dist/db/canonicalStore",\n',
  '    "dist/db/migrations",\n',
  '    "node_modules/better-sqlite3",\n',
  '    "node_modules/bindings",\n',
  '    "node_modules/file-uri-to-path",\n',
  '  ])\n',
  '    immutableCodeTree(path.join(appRoot, directory));\n',
  '  for (const file of [\n',
  '    "dist/main.js",\n',
  '    "dist/db/migrate.js",\n',
  '    "dist/runtime/canonicalStoreMaintenance.js",\n',
  '  ])\n',
  '    regular(path.join(appRoot, file), { owner: 0, readonly: true });\n',
  '  const require = createRequire(path.join(appRoot, "package.json"));\n',
  '  const core = require(path.join(appRoot, "dist/db/canonicalStore/index.js"));\n',
  '  if (\n',
  '    typeof core.acquireWriterFence !== "function" ||\n',
  '    typeof core.inspectCandidate !== "function"\n',
  '  )\n',
  '    blocked("ImageFloorMissing");\n',
  '  return core;\n',
  '}\n',
  'export async function measureSource(\n',
  '  pins,\n',
  '  {\n',
  '    core = trustedCore(),\n',
  '    procRoot = "/proc",\n',
  '    expectedUid = 1001,\n',
  '    scratchRoot = "/tmp",\n',
  '    readProcess = verifyLiveProcess,\n',
  '  } = {},\n',
  ') {\n',
  '  const reportPath = path.join(\n',
  '    pins.stateDir,\n',
  '    ".canonical-store",\n',
  '    "maintenance",\n',
  '    pins.maintenanceId,\n',
  '    `${pins.podUid}.json`,\n',
  '  );\n',
  '  const report = validateRuntimeClosure(\n',
  '    readJson(confined(pins.stateDir, reportPath)),\n',
  '    pins,\n',
  '  );\n',
  '  const process = readProcess(report, { procRoot, expectedUid });\n',
  '  if (report.source.dbPath !== pins.sourcePath) blocked("SourceExportRequired");\n',
  '  noSqliteHandles([pins.sourcePath], procRoot);\n',
  '  // A writable same-PVC EXCLUSIVE fence is an actual contention test. Report\n',
  '  // ownership/booleans cannot grant this capability or prove an empty store.\n',
  '  const fence = core.acquireWriterFence({\n',
  '    stateDir: pins.stateDir,\n',
  '    timeoutMs: 1000,\n',
  '  });\n',
  '  let inspection;\n',
  '  try {\n',
  '    fence.assertHeld();\n',
  '    inspection = await core.inspectCandidate(path.dirname(pins.sourcePath), {\n',
  '      root: path.dirname(pins.sourcePath),\n',
  '      scratchRoot,\n',
  '      scratchDir: path.join(scratchRoot, ".canonical-store-proof"),\n',
  '      binding: { hostUid: pins.hostUid, pvcUid: pins.pvcUid },\n',
  '      fence,\n',
  '      timeoutMs: 120000,\n',
  '    });\n',
  '    const after = readProcess(report, { procRoot, expectedUid });\n',
  '    if (objectHash(after) !== objectHash(process))\n',
  '      blocked("WriterIdentityChanged");\n',
  '    noSqliteHandles([pins.sourcePath], procRoot);\n',
  '    fence.assertHeld();\n',
  '    const writer = {\n',
  '      pid: process.pid,\n',
  '      startTimeTicks: process.startTimeTicks,\n',
  '      uid: expectedUid,\n',
  '      argvHash: process.argvHash,\n',
  '      executable: process.executable,\n',
  '      script: process.script,\n',
  '      mainSha256: process.mainSha256,\n',
  '    };\n',
  '    const facts = {\n',
  '      factVersion: 1,\n',
  '      hostUid: pins.hostUid,\n',
  '      pvcUid: pins.pvcUid,\n',
  '      podUid: pins.podUid,\n',
  '      maintenanceId: pins.maintenanceId,\n',
  '      process: writer,\n',
  '      source: {\n',
  '        mode: "sqlite",\n',
  '        dbPath: pins.sourcePath,\n',
  '        sourceSnapshotHash: inspection.sourceHash,\n',
  '        catalogHash: inspection.catalogHash,\n',
  '      },\n',
  '      fence: "sqlite-exclusive",\n',
  '    };\n',
  '    const proof = {\n',
  '      proofVersion: 1,\n',
  '      outcome: "ok",\n',
  '      hostUid: pins.hostUid,\n',
  '      pvcUid: pins.pvcUid,\n',
  '      sourcePodUid: pins.podUid,\n',
  '      requestId: pins.requestId,\n',
  '      maintenanceId: pins.maintenanceId,\n',
  '      sourceClass: pins.sourceClass,\n',
  '      sourceMode: "sqlite",\n',
  '      sourcePath: pins.sourcePath,\n',
  '      writerStopped: true,\n',
  '      sourceSnapshotHash: inspection.sourceHash,\n',
  '      catalogHash: inspection.catalogHash,\n',
  '      sourceSchemaVersion: inspection.schemaVersion,\n',
  '      closedWitnessHash: objectHash(facts),\n',
  '      runtimeClosureHash: objectHash(report),\n',
  '      ...writer,\n',
  '    };\n',
  '    return { proof, facts, report, sourceFiles: inspection.sourceFiles };\n',
  '  } finally {\n',
  '    try {\n',
  '      inspection?.dispose();\n',
  '    } finally {\n',
  '      fence.close();\n',
  '    }\n',
  '  }\n',
  '}\n',
  'export function readBootstrapReceipt(root, exportId) {\n',
  '  if (\n',
  '    !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(\n',
  '      exportId,\n',
  '    )\n',
  '  )\n',
  '    blocked("JournalInvalid");\n',
  '  const directory = path.join(root, ".canonical-store-bootstrap", exportId);\n',
  '  return {\n',
  '    directory,\n',
  '    receipt: readJson(confined(root, path.join(directory, "receipt.json"))),\n',
  '  };\n',
  '}\n',
  'export async function verifyPhysicalReceipt(pins, options = {}) {\n',
  '  const measured = await measureSource(pins, options);\n',
  '  if (pins.sourceClass === "sqlite-pvc") return measured.proof;\n',
  '  const { directory, receipt } = readBootstrapReceipt(pins.root, pins.exportId);\n',
  '  if (\n',
  '    receipt.receiptVersion !== 1 ||\n',
  '    receipt.exportId !== pins.exportId ||\n',
  '    receipt.hostUid !== pins.hostUid ||\n',
  '    receipt.pvcUid !== pins.pvcUid ||\n',
  '    receipt.sourcePodUid !== pins.podUid ||\n',
  '    receipt.maintenanceId !== pins.maintenanceId ||\n',
  '    receipt.sourceMode !== "sqlite" ||\n',
  '    receipt.manifestHash !== pins.manifestHash ||\n',
  '    receipt.sourceSnapshotHash !== measured.proof.sourceSnapshotHash ||\n',
  '    receipt.catalogHash !== measured.proof.catalogHash ||\n',
  '    receipt.closedWitnessHash !== measured.proof.closedWitnessHash ||\n',
  '    receipt.runtimeClosureHash !== measured.proof.runtimeClosureHash ||\n',
  '    objectHash(receipt.closedWriter) !== objectHash(measured.facts.process)\n',
  '  )\n',
  '    blocked("AdoptBindingMismatch");\n',
  '  const retained = readJson(\n',
  '    confined(pins.root, path.join(directory, "runtime-closure.json")),\n',
  '  );\n',
  '  const facts = readJson(\n',
  '    confined(pins.root, path.join(directory, "closed-facts.json")),\n',
  '  );\n',
  '  if (\n',
  '    objectHash(retained) !== receipt.runtimeClosureHash ||\n',
  '    objectHash(facts) !== receipt.closedWitnessHash\n',
  '  )\n',
  '    blocked("JournalInvalid");\n',
  '  return {\n',
  '    ...measured.proof,\n',
  '    exportId: pins.exportId,\n',
  '    manifestHash: receipt.manifestHash,\n',
  '  };\n',
  '}\n',
  'export function parsedPins(argv) {\n',
  '  const names = [\n',
  '    "host-name",\n',
  '    "namespace",\n',
  '    "host-uid",\n',
  '    "pvc-uid",\n',
  '    "pod-uid",\n',
  '    "request-id",\n',
  '    "maintenance-id",\n',
  '    "export-id",\n',
  '    "manifest-hash",\n',
  '    "root",\n',
  '    "source-class",\n',
  '    "state-dir",\n',
  '    "source-path",\n',
  '  ];\n',
  '  const { values } = parseArgs({\n',
  '    args: argv,\n',
  '    options: Object.fromEntries(\n',
  '      names.map((name) => [name, { type: "string" }]),\n',
  '    ),\n',
  '    strict: true,\n',
  '  });\n',
  '  for (const name of [\n',
  '    "host-name",\n',
  '    "namespace",\n',
  '    "host-uid",\n',
  '    "pvc-uid",\n',
  '    "pod-uid",\n',
  '    "request-id",\n',
  '    "maintenance-id",\n',
  '    "state-dir",\n',
  '    "source-path",\n',
  '    "source-class",\n',
  '  ])\n',
  '    if (!values[name]) blocked("JournalInvalid");\n',
  '  if (\n',
  '    !["sqlite-pvc", "sqlite-external-exported"].includes(values["source-class"])\n',
  '  )\n',
  '    blocked("StoreModeUnknown");\n',
  '  if (values["source-class"] === "sqlite-external-exported")\n',
  '    for (const name of ["root", "export-id", "manifest-hash"])\n',
  '      if (!values[name]) blocked("JournalInvalid");\n',
  '  for (const name of ["state-dir", "source-path"])\n',
  '    if (!path.isAbsolute(values[name])) blocked("LayoutUnsafe");\n',
  '  return {\n',
  '    hostName: values["host-name"],\n',
  '    namespace: values.namespace,\n',
  '    hostUid: values["host-uid"],\n',
  '    pvcUid: values["pvc-uid"],\n',
  '    podUid: values["pod-uid"],\n',
  '    requestId: values["request-id"],\n',
  '    maintenanceId: values["maintenance-id"],\n',
  '    exportId: values["export-id"],\n',
  '    manifestHash: values["manifest-hash"],\n',
  '    sourceClass: values["source-class"],\n',
  '    stateDir: path.resolve(values["state-dir"]),\n',
  '    sourcePath: path.resolve(values["source-path"]),\n',
  '    root: values.root ? path.resolve(values.root) : undefined,\n',
  '  };\n',
  '}\n',
  'const invoked =\n',
  '  process.argv[1] === "-"\n',
  '    ? import.meta.url.endsWith("/[eval1]")\n',
  '    : process.argv[1] &&\n',
  '      path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);\n',
  'if (invoked) {\n',
  '  try {\n',
  '    const pins = parsedPins(process.argv.slice(2));\n',
  '    const revision = await freshChallenge(pins, "prepare");\n',
  '    const proof = await verifyPhysicalReceipt(pins);\n',
  '    if ((await freshChallenge(pins, "prepare")) !== revision)\n',
  '      blocked("AdoptBindingMismatch");\n',
  '    process.stdout.write(`${JSON.stringify(proof)}\\n`);\n',
  '  } catch (error) {\n',
  '    process.stdout.write(\n',
  '      `${JSON.stringify({ proofVersion: 1, outcome: "blocked", reason: error.reason ?? "HostAuthorityUnavailable" })}\\n`,\n',
  '    );\n',
  '    process.exitCode = 1;\n',
  '  }\n',
  '}\n',
].join('')
