import jwt from 'jsonwebtoken'
import { createPublicKey, randomUUID } from 'node:crypto'
import { config } from '../config.js'
import type { PluginWorkloadSdkPromptTarget } from './pluginWorkloadSdkDb.js'

// This is an authorization artifact, not a credential. It binds the exact
// already-authorized target to one invocation so mcp-host cannot be tricked
// into resolving a different slot from a caller-supplied policy response.
export const PLUGIN_SDK_CREDENTIAL_TICKET_AUDIENCE = 'plugin-sdk-credential-broker'
/** Short-lived by design: fallbacks receive a new ticket just before use. */
export const PLUGIN_SDK_CREDENTIAL_TICKET_TTL_SECONDS = 60

export type PluginWorkloadSdkCredentialTicketClaims = {
  /** Unique ticket identity, generated by the issuer rather than the caller. */
  jti: string
  sub: string
  recipeNamespace: string
  recipeName: string
  invocationId: string
  attemptGeneration: number
  providerAttemptId: string
  providerAttemptIndex: number
  targetRef: string
  provider: string
  model: string
  credentialSlot: string
  policyRevision: number
  policyHash: string
  typ: 'plugin-sdk-credential-ticket'
}

export type IssuedPluginWorkloadSdkCredentialTicket = {
  credentialTicket: string
  claims: PluginWorkloadSdkCredentialTicketClaims
}

export function issuePluginWorkloadSdkCredentialTicket(input: {
  recipeNamespace: string
  recipeName: string
  invocationId: string
  attemptGeneration: number
  providerAttemptId: string
  providerAttemptIndex: number
  target: PluginWorkloadSdkPromptTarget
  policyRevision: number
  policyHash: string
}): string {
  return issuePluginWorkloadSdkCredentialTicketWithClaims(input).credentialTicket
}

/**
 * Issues a ticket plus its issuer-generated identity so control-api can record
 * exactly one future redemption. This is internal control-plane data; callers
 * must never choose the jti.
 */
export function issuePluginWorkloadSdkCredentialTicketWithClaims(input: {
  recipeNamespace: string
  recipeName: string
  invocationId: string
  attemptGeneration: number
  providerAttemptId: string
  providerAttemptIndex: number
  target: PluginWorkloadSdkPromptTarget
  policyRevision: number
  policyHash: string
}): IssuedPluginWorkloadSdkCredentialTicket {
  const claims: PluginWorkloadSdkCredentialTicketClaims = {
    jti: randomUUID(),
    sub: `${input.recipeNamespace}/${input.recipeName}`,
    recipeNamespace: input.recipeNamespace,
    recipeName: input.recipeName,
    invocationId: input.invocationId,
    attemptGeneration: input.attemptGeneration,
    providerAttemptId: input.providerAttemptId,
    providerAttemptIndex: input.providerAttemptIndex,
    targetRef: input.target.targetRef,
    provider: input.target.provider,
    model: input.target.model,
    credentialSlot: input.target.credentialSlot,
    policyRevision: input.policyRevision,
    policyHash: input.policyHash,
    typ: 'plugin-sdk-credential-ticket',
  }
  return {
    credentialTicket: jwt.sign(claims, config.adminJwtPrivateKey, {
      algorithm: 'RS256',
      issuer: config.adminJwtIssuer,
      audience: PLUGIN_SDK_CREDENTIAL_TICKET_AUDIENCE,
      expiresIn: PLUGIN_SDK_CREDENTIAL_TICKET_TTL_SECONDS,
    }),
    claims,
  }
}

export function verifyPluginWorkloadSdkCredentialTicket(
  ticket: string
): PluginWorkloadSdkCredentialTicketClaims | null {
  try {
    const publicKey = createPublicKey(config.adminJwtPrivateKey).export({
      type: 'spki',
      format: 'pem',
    })
    const verified = jwt.verify(ticket, publicKey, {
      algorithms: ['RS256'],
      issuer: config.adminJwtIssuer,
      audience: PLUGIN_SDK_CREDENTIAL_TICKET_AUDIENCE,
    })
    if (typeof verified !== 'object' || verified === null) return null
    const claims = verified as jwt.JwtPayload
    if (
      typeof claims.jti !== 'string' ||
      claims.jti.length === 0 ||
      typeof claims.sub !== 'string' ||
      typeof claims.recipeNamespace !== 'string' ||
      typeof claims.recipeName !== 'string' ||
      typeof claims.invocationId !== 'string' ||
      typeof claims.attemptGeneration !== 'number' ||
      !Number.isInteger(claims.attemptGeneration) ||
      claims.attemptGeneration < 1 ||
      typeof claims.providerAttemptId !== 'string' ||
      claims.providerAttemptId.length === 0 ||
      typeof claims.providerAttemptIndex !== 'number' ||
      !Number.isInteger(claims.providerAttemptIndex) ||
      claims.providerAttemptIndex < 1 ||
      typeof claims.targetRef !== 'string' ||
      typeof claims.provider !== 'string' ||
      typeof claims.model !== 'string' ||
      typeof claims.credentialSlot !== 'string' ||
      typeof claims.policyRevision !== 'number' ||
      typeof claims.policyHash !== 'string' ||
      claims.typ !== 'plugin-sdk-credential-ticket'
    ) {
      return null
    }
    return claims as unknown as PluginWorkloadSdkCredentialTicketClaims
  } catch {
    return null
  }
}
