import type { CreateFlowLoadingConfig } from '@components/CreateFlowSkeleton/types'

export const CREATE_FLOW_LOADING = {
  createAgent: {
    iconKey: 'robot',
    title: 'Create agent',
    subtitle: 'Provision a new agent with connectors, credentials, and access.',
    backLabel: 'Back to agents',
    steps: ['Agent', 'Model & Credentials', 'Access', 'Add Connectors'],
    stepFlowClassName: 'cu-create-step-flow--4',
  },
  createCommunicationChannel: {
    iconKey: 'broadcast',
    title: 'Create communication channel',
    subtitle: 'Define channel routing and link it to an agent.',
    backLabel: 'Back to channels',
    steps: ['Channel', 'Routing'],
    stepFlowClassName: 'cu-create-step-flow--2',
  },
  createContext: {
    iconKey: 'group-work',
    title: 'Create context',
    subtitle: 'Define a new context and attach connectors.',
    backLabel: 'Back to contexts',
    steps: ['Context', 'Connectors'],
    stepFlowClassName: 'cu-create-step-flow--2',
  },
  createControlAdmin: {
    iconKey: 'settings',
    title: 'Invite admin',
    subtitle: 'Invite a new Control UI admin.',
    backLabel: 'Back to admins',
    steps: ['Email', 'Review'],
    stepFlowClassName: 'cu-create-step-flow--2',
  },
  createConnector: {
    iconKey: 'cable',
    title: 'Create connector',
    subtitle: 'Register a new connector and optionally create its managed deployment metadata.',
    backLabel: 'Back to connectors',
    steps: ['Connector', 'Access', 'Secrets'],
    stepFlowClassName: 'cu-create-step-flow--3',
  },
  createMember: {
    iconKey: 'users',
    title: 'Create member',
    subtitle: 'Create a pending invitation and send the invitation email.',
    backLabel: 'Back to members',
    steps: ['Member', 'Team'],
    stepFlowClassName: 'cu-create-step-flow--2',
  },
  createSecret: {
    iconKey: 'key',
    title: 'Create secret',
    subtitle: 'Store credentials for LLM providers, connectors, or recipes.',
    backLabel: 'Back to secrets',
    steps: ['Secret', 'Values'],
    stepFlowClassName: 'cu-create-step-flow--2',
  },
  createSharedFileSystem: {
    iconKey: 'shared-files',
    title: 'Create SharedFileSystem',
    subtitle: 'Provision workspace storage that Contexts can mount read-only into agent pods.',
    backLabel: 'Back to Agent Files',
    steps: ['Storage', 'Access', 'Folders'],
    stepFlowClassName: 'cu-create-step-flow--3',
  },
  createTeam: {
    iconKey: 'users',
    title: 'Create team',
    subtitle: 'Create a team now. You can assign a leader later.',
    backLabel: 'Back to teams',
    steps: ['Team', 'Members', 'Access', 'Agents'],
    stepFlowClassName: 'cu-create-step-flow--4 cu-team-create-panel',
  },
  installRegistryEntry: {
    iconKey: 'store',
    title: 'Install from Marketplace',
    subtitle: 'Install a Marketplace entry into your cluster.',
    backLabel: 'Back to Marketplace',
    steps: ['Package', 'Credentials', 'Install'],
    stepFlowClassName: 'cu-create-step-flow--3',
  },
  installPlugin: {
    iconKey: 'workflow',
    title: 'Install Plugin',
    subtitle: 'Prepare a plugin manifest, validate policy, and deploy it.',
    backLabel: 'Back to plugins',
    steps: ['Manifest', 'Review', 'Defaults', 'Access & deploy'],
    stepFlowClassName: 'cu-create-step-flow--4',
  },
  editPlugin: {
    iconKey: 'workflow',
    title: 'Edit Plugin',
    subtitle: 'Update the plugin manifest, review policy, and redeploy it.',
    backLabel: 'Back to plugin',
    steps: ['Manifest', 'Review', 'Defaults', 'Access & deploy'],
    stepFlowClassName: 'cu-create-step-flow--4',
  },
  publishRegistryEntry: {
    iconKey: 'store',
    title: 'Publish to Marketplace',
    subtitle: 'Publish connectors or plugins to the Marketplace with versioned metadata.',
    backLabel: 'Back to Marketplace',
    steps: ['Entry', 'Metadata', 'Package', 'Review'],
    stepFlowClassName: 'cu-create-step-flow--4',
  },
} satisfies Record<string, CreateFlowLoadingConfig>
