apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: rpc-proxy
  name: rpc-proxy
  namespace: rpc-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rpc-proxy
  name: rpc-proxy
  namespace: rpc-proxy
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rpc-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rpc-proxy
    spec:
      automountServiceAccountToken: false
      containers:
      - envFrom:
        - configMapRef:
            name: rpc-proxy-config
        - secretRef:
            name: rpc-proxy-secrets
        image: clerum/rpc-proxy:0.9.5
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 8
          periodSeconds: 12
          successThreshold: 1
          timeoutSeconds: 2
        name: rpc-proxy
        ports:
        - containerPort: 8094
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 8
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: rpc-proxy
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rpc-proxy
  name: rpc-proxy
  namespace: rpc-proxy
spec:
  ports:
  - name: http
    port: 8094
    protocol: TCP
    targetPort: http
  selector:
    app: rpc-proxy
  type: ClusterIP
