apiVersion: v1
kind: Secret
metadata:
  name: inter-service-tokens
  namespace: control-plane
type: Opaque
stringData:
  external-rest-api-token: "minikube-external-rest-api-service-token"
  rpc-proxy-token: "minikube-rpc-proxy-service-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: control-postgres
  namespace: control-plane
type: Opaque
stringData:
  POSTGRES_DB: profiles
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
