apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../minikube

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: control-ui
      namespace: control-plane
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: control-ui
        namespace: control-plane
  - target:
      version: v1
      kind: Service
      name: control-ui
      namespace: control-plane
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: control-ui
        namespace: control-plane
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: profile-ui
      namespace: profiles
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: profile-ui
        namespace: profiles
  - target:
      version: v1
      kind: Service
      name: profile-ui
      namespace: profiles
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: profile-ui
        namespace: profiles
