export const projectRoots = [
  'channel-reader',
  'control-api',
  'control-ui',
  'desktop-app',
  'external-rest-api',
  'host-context-controller',
  'mcp-host',
  'mcp-proxy',
  'mcp-servers',
  'packages/workflow-sdk',
  'profile-ui',
  'rpc-proxy',
  'stdio-bridge',
  'tests/e2e',
  'workflow-recipes',
]

export const packageRoots = [
  'channel-reader',
  'control-api',
  'control-ui',
  'desktop-app',
  'external-rest-api',
  'host-context-controller',
  'mcp-host',
  'mcp-proxy',
  'mcp-servers',
  'mcp-servers/doc-generator',
  'mcp-servers/web-search',
  'packages/workflow-sdk',
  'profile-ui',
  'rpc-proxy',
  'stdio-bridge',
  'tests/e2e',
  'tests/e2e/fixtures',
  'tests/e2e/fixtures/mock-mcp-server',
  'tests/e2e/fixtures/mock-secrets-server',
  'tests/e2e/fixtures/mock-stdio-mcp-server',
  'tests/e2e/playwright',
  'workflow-recipes',
  'workflow-recipes/tests/e2e',
]

export const rootFormatTargets = [
  'commitlint.config.cjs',
  'package.json',
  'prettier.config.cjs',
  '.prettierignore',
  'scripts/precommit',
  'scripts/prettier',
]
