apiVersion: v1
kind: ServiceAccount
metadata:
  name: clerum-workflow-approval-request-reader
  namespace: channels
  labels:
    app.kubernetes.io/name: workflow-approval-request-reader
    app.kubernetes.io/part-of: clerum
