apiVersion: v1
kind: Service
metadata:
  name: workflow-approval-request-reader
  namespace: channels
  labels:
    app.kubernetes.io/name: workflow-approval-request-reader
    app.kubernetes.io/part-of: clerum
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: workflow-approval-request-reader
  ports:
  - name: http
    port: 8098
    targetPort: http
    protocol: TCP
